- hosts: ui
  tasks:
    - debug: msg="ui task"
    - ping:

- hosts: db
  tasks:
    - debug: msg="db task"
    - ping:

- hosts: all
  tasks:
    - debug: msg="all task"
    - ping:

- hosts: localhost
  tasks:
    - debug: msg="morph_appname is {{ morph_appname }}"
